# Setup Julia image as parent image
FROM julia:1.12.5

# Ger LaTeX and divpng (for latexstrings)
RUN apt-get update && apt-get -qy install texlive-latex-base dvipng

# Working directory
WORKDIR /app

# Copy working diretory
COPY . /app

# # Run everything
# CMD ["julia", "--project=.", "runEverything.jl"]